# Generated by Django 4.1.4 on 2022-12-14 14:46

from django.db import migrations, models
import player.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, max_length=256)),
                ('artist_profileImage', models.ImageField(blank=True, upload_to=player.models.Artists_Profile_Images)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
